(function(){
  const cfg=window.RENUKA_SUPABASE_CONFIG||{};
  const loginCard=document.getElementById('loginCard'), adminCard=document.getElementById('adminCard'), loginMsg=document.getElementById('loginMsg'), adminMsg=document.getElementById('adminMsg');
  let client=null, all=[];
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function show(el,msg,err=false){el.textContent=msg;el.style.display='block';el.classList.toggle('danger',err)}
  if(!cfg.url||!cfg.anonKey||!window.supabase){show(loginMsg,'Supabase configuration भरलेली नाही. supabase-config.js मध्ये URL आणि public anon key भरा.',true);$('loginBtn').disabled=true;return;}
  client=window.supabase.createClient(cfg.url,cfg.anonKey);
  const today=()=>new Date().toISOString().slice(0,10);
  $('adminDate').value=today();
  $('loginBtn').addEventListener('click',async()=>{loginMsg.style.display='none';const email=$('loginEmail').value.trim(),password=$('loginPassword').value;if(!email||!password){show(loginMsg,'ई-मेल आणि पासवर्ड भरा.',true);return;}const {error}=await client.auth.signInWithPassword({email,password});if(error){show(loginMsg,'लॉगिन अयशस्वी: '+error.message,true);return;}await start();});
  $('logoutBtn').addEventListener('click',async()=>{await client.auth.signOut();adminCard.classList.add('hidden');loginCard.classList.remove('hidden');});
  async function start(){loginCard.classList.add('hidden');adminCard.classList.remove('hidden');await load();}
  async function load(){show(adminMsg,'नोंदी लोड होत आहेत…');const {data,error}=await client.from('renuka_registrations').select('*').order('created_at',{ascending:false});if(error){show(adminMsg,'नोंदी लोड करता आल्या नाहीत: '+error.message,true);return;}all=data||[];adminMsg.style.display='none';render();}
  function dateOf(r){return (r.created_at||'').slice(0,10)}
  function render(){const q=$('adminSearch').value.trim().toLowerCase(),date=$('adminDate').value,kind=$('adminFilter').value,pf=$('adminPrasadFilter').value;const grouped=new Map();for(const r of all){const key=(r.mobile||r.email||r.name||'').replace(/\s+/g,'').toLowerCase();if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(r)}let people=[...grouped.values()].map(rs=>{const d=rs.find(x=>x.registration_type==='donation'),s=rs.find(x=>x.registration_type==='service'),b=s||d||rs[0];return {key:rs.map(x=>x.id).join('|'),rows:rs,name:b.name,mobile:b.mobile,email:b.email,address:b.address,city:b.city,pin:b.pin,donation:d,service:s,sent:rs.every(x=>x.prasad_sent),tracking:rs.map(x=>x.tracking_no).filter(Boolean).join(' / '),amount:rs.reduce((a,x)=>a+Number(x.amount||0),0)}});
    people=people.filter(p=>{const text=[p.name,p.mobile,p.email,p.address,p.city,p.pin,p.donation?.utr,p.service?.utr,p.donation?.receipt_no,p.service?.receipt_no].join(' ').toLowerCase();if(q&&!text.includes(q))return false;if(date&&!p.rows.some(r=>dateOf(r)===date))return false;if(kind==='donation'&&(!p.donation||p.service))return false;if(kind==='service'&&(!p.service||p.donation))return false;if(kind==='both'&&(!p.donation||!p.service))return false;if(pf==='pending'&&p.sent)return false;if(pf==='sent'&&!p.sent)return false;return true});
    $('summary').innerHTML=`<span>भक्त: ${people.length}</span><span>देणगी: ${people.filter(p=>p.donation).length}</span><span>पूजा / अभिषेक: ${people.filter(p=>p.service).length}</span><span>दोन्ही: ${people.filter(p=>p.donation&&p.service).length}</span><span>प्रसाद बाकी: ${people.filter(p=>!p.sent).length}</span>`;
    $('rows').innerHTML=people.length?people.map(p=>{const tags=[p.donation?'देणगी':'',p.service?'पूजा / अभिषेक':''].filter(Boolean).map(x=>`<span class="tag">${x}</span>`).join(' ');const rs=p.rows;return `<tr><td><strong>${esc(p.name)}</strong><br><small>${esc(p.email||'')}</small></td><td>${esc(p.mobile)}</td><td>${tags}</td><td>₹${p.amount.toLocaleString('en-IN')}</td><td>${esc([p.address,p.city,p.pin].filter(Boolean).join(', '))}</td><td>${rs.map(r=>`<div><b>${esc(r.utr)}</b><br><small>${esc(r.receipt_no)}</small></div>`).join('<hr>')}</td><td><button class="status-btn ${p.sent?'sent':''}" data-key="${esc(p.key)}">${p.sent?'☑ प्रसाद पाठवला':'☐ प्रसाद पाठवायचा आहे'}</button></td><td><div class="track"><input data-track="${esc(p.key)}" value="${esc(p.tracking)}" placeholder="Tracking No."><button class="btn btn-outline" data-save="${esc(p.key)}">जतन</button></div></td></tr>`}).join(''):'<tr><td colspan="8">या फिल्टरसाठी नोंद उपलब्ध नाही.</td></tr>';
  }
  document.addEventListener('click',async e=>{const b=e.target.closest('[data-key]');if(b){const ids=b.dataset.key.split('|');const current=all.filter(r=>ids.includes(r.id));const next=!current.every(r=>r.prasad_sent);const {error}=await client.from('renuka_registrations').update({prasad_sent:next}).in('id',ids);if(error)show(adminMsg,error.message,true);else await load();}const s=e.target.closest('[data-save]');if(s){const ids=s.dataset.save.split('|'),input=document.querySelector(`[data-track="${CSS.escape(s.dataset.save)}"]`),value=input?.value.trim()||'';const {error}=await client.from('renuka_registrations').update({tracking_no:value}).in('id',ids);if(error)show(adminMsg,error.message,true);else await load();}});
  ['adminSearch','adminDate','adminFilter','adminPrasadFilter'].forEach(id=>$(id).addEventListener(id==='adminSearch'?'input':'change',render));$('refreshBtn').addEventListener('click',load);
  $('exportBtn').addEventListener('click',()=>{const rows=[...document.querySelectorAll('#rows tr')];if(!rows.length)return;const q=$('adminSearch').value.trim().toLowerCase(),date=$('adminDate').value,kind=$('adminFilter').value,pf=$('adminPrasadFilter').value;const data=all.filter(r=>{const text=[r.name,r.mobile,r.email,r.utr,r.receipt_no,r.address,r.city,r.pin].join(' ').toLowerCase();if(q&&!text.includes(q))return false;if(date&&dateOf(r)!==date)return false;if(kind!=='all'&&((kind==='donation'&&r.registration_type!=='donation')||(kind==='service'&&r.registration_type!=='service')))return false;if(pf==='pending'&&r.prasad_sent)return false;if(pf==='sent'&&!r.prasad_sent)return false;return true});const out=[['दिनांक','नोंद','नाव','मोबाईल','ई-मेल','सेवा प्रकार','रक्कम','UTR','पावती क्र.','पत्ता','शहर','PIN','प्रसाद','Tracking No.'],...data.map(r=>[dateOf(r),r.registration_type==='donation'?'देणगी':'पूजा / अभिषेक',r.name,r.mobile,r.email||'',r.service_type||'',r.amount,r.utr,r.receipt_no,r.address||'',r.city||'',r.pin||'',r.prasad_sent?'पाठवला':'पाठवायचा आहे',r.tracking_no||''])];const csv='\ufeff'+out.map(a=>a.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='renuka-darbar-daily-registrations.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
  client.auth.getSession().then(({data})=>{if(data.session)start();});
})();
